### ISSUE TITLE
Hot Reload Error

### ISSUE THREAD

**Issue by mrtnkrstn** [juliansteenbakker/mobile_scanner#425]
Using Hot Reload on either iOS or Android on view with camera causes `MobileScanner: Called start() while already started!` error.

Repro steps: 

1. build example app to device
2. open any camera screen
3. do Hot Reload

**Comment by kamami** [comment]
Same

**Comment by zunimc** [comment]
I have the same issue, whether hot reload or hot restart, the camera view goes black. This also happens when returning from another page or tab.

I tried using the latest 3.0.0 beta 4 and it works BUT scan performance is remarkably worse. I'm staying on v2.1.0 for now.

**Comment by juliansteenbakker** [comment]
I have released version 3.0.0 which should fix this issue.

**Comment by zunimc** [comment]
Hi Julian, I tried this new version on a brand new flutter project and it works when running **flutter run**.

Issue remains tho, as soon as I hot reload camera crashes.

`flutter: Called start() while starting.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MobileScannerException: code genericError, message: Called start() while already started!
#0      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:210:7)
<asynchronous suspension>`
