### ISSUE TITLE
[BUG] Higher minimum deployment target required

### ISSUE THREAD

**Issue by svprdga** [juliansteenbakker/mobile_scanner#478]
I am having the following error when building the iOS target:

```
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/BarcodeScanning":
  In Podfile:
    GoogleMLKit/BarcodeScanning (= 2.6.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0)

Specs satisfying the `GoogleMLKit/BarcodeScanning (= 2.6.0), GoogleMLKit/BarcodeScanning (~> 3.2.0)` dependency were found, but they required a higher minimum deployment target.
```

I have tried:
1. Uncommenting the first file in Podfile `platform :ios, '11.0'`
2. Also set `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'` in Podfile
3. Set the version within Xcode

I have tried with many versions, `11.0`,`13.7` and `14.7`

In each change I do:
- `flutter clean` in the project root
- `pod deintegrate` in `/ios`
- `rm -rf .symlinks` in `/ios`
- `rm -rf Podfile.lock` in `/ios`
- `flutter pub get` in the project root
- `pod install --repo-update` in `/ios`

Data:
- Plugin: `mobile_scanner: ^2.1.0`
- Flutter version: `3.7.1`

**Comment by juliansteenbakker** [comment]
I have released version 3.0.0 which should fix this issue.

**Comment by kekko7072** [comment]
@juliansteenbakker Thanks for the release very appreciated.
Unfortunately I'm still having the issue with `firebase_auth` and `google_sign_in_ios` .

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.2.6, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 6.2) was resolved to 6.2.4, which depends on
        GTMSessionFetcher/Core (< 3.0, >= 1.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.0.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitCommon (~> 8.0) was resolved to 8.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

```

There is a way to fix this ?

**Comment by pyciko** [comment]
+1. Still having the issue after update
`[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.2.6, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 3.0.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        GoogleMLKit/MLKitCore (= 3.2.0) was resolved to 3.2.0, which depends on
          MLKitCommon (~> 8.0.0) was resolved to 8.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)`

**Comment by kyleorin** [comment]
got the same issue here, anyone knows how to fix this?

**Comment by videah** [comment]
Running `pod repo update` and `pod update` in my ios folder fixed this issue for me.
