### ISSUE TITLE
Flutter 3.10 Permission Denied in flutter web...

### ISSUE THREAD

**Issue by Zelfapp** [juliansteenbakker/mobile_scanner#632]
My Flutter app runs on the web. I'm getting permission denied on Android using the Chrome browser. README doesn't have any android permission info or anything I need to include in index.html? How do I get past this on Flutter web?

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/11559805/4becc737-8138-4db4-85ff-dcf596573ae7)

Version: mobile_scanner: ^3.2.0

```dart
late final MobileScannerController _controller = MobileScannerController();

MobileScanner(
    controller: _controller,
    fit: BoxFit.contain,
    errorBuilder: (
      BuildContext context,
      MobileScannerException error,
      Widget? child,
    ) {
      return ScannerErrorWidget(error: error);
    },
    onDetect: widget.onDetect,
  )

class ScannerErrorWidget extends StatelessWidget {
  const ScannerErrorWidget({super.key, required this.error});

  final MobileScannerException error;

  @override
  Widget build(BuildContext context) {
    String errorMessage;

    switch (error.errorCode) {
      case MobileScannerErrorCode.controllerUninitialized:
        errorMessage = 'Controller not ready.';
        break;
      case MobileScannerErrorCode.permissionDenied:
        errorMessage = 'Permission denied';
        break;
      default:
        errorMessage = 'Generic Error';
        break;
    }

    return ColoredBox(
      color: Colors.black,
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Padding(
              padding: EdgeInsets.only(bottom: 16),
              child: Icon(Icons.error, color: Colors.white),
            ),
            Text(
              errorMessage,
              style: const TextStyle(color: Colors.white),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by brasizza** [comment]
Same here

**Comment by Zelfapp** [comment]
@brasizza @klokoleva please put a thumbs up on my original issue so we can get it more attention from the dev on this package.

**Comment by brasizza** [comment]
@Zelfapp , we fixed  putting this on index.html

  <script type="text/javascript" src="https://unpkg.com/@zxing/library@0.20.0/umd/index.min.js"></script>
and   mobile_scanner: ^3.0.0

**Comment by Zelfapp** [comment]
@brasizza that fixes it for me. Thanks.

**Comment by VictorTan978** [comment]
My error is without permission denies. The permission already approved but still show the exclamation mark and black background.
